### ISSUE TITLE
Fail to deploy a CF v238 on single node

### ISSUE THREAD

**Issue by gossion** [cloudfoundry/cf-release#1001]
we have a simple template which has all jobs running on a single node for some test purpose. The template was deployed  successfully in previous version of cf release, however, in the latest cf release v238, we got the error saying that it fail to pre-start cloud_controller_ng. 

```
Director task 871
  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started creating missing vms > cf_z1/0 (0a49d103-ffdc-40b4-adcf-18b531ddaf25). Done (00:02:28)

  Started updating job cf_z1 > cf_z1/0 (0a49d103-ffdc-40b4-adcf-18b531ddaf25) (canary). Failed: Action Failed get_task: Task 41f22761-2a85-4147-4040-3ce6300e593b result: 1 of 9 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: cloud_controller_clock, nats_stream_forwarder, nats, etcd_metrics_server, cloud_controller_worker, etcd, consul_agent, uaa. (00:05:48)

Error 450001: Action Failed get_task: Task 41f22761-2a85-4147-4040-3ce6300e593b result: 1 of 9 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: cloud_controller_clock, nats_stream_forwarder, nats, etcd_metrics_server, cloud_controller_worker, etcd, consul_agent, uaa.

Task 871 error

```

From /var/vcap/sys/log/cloud_controller_ng/pre-start.stderr.log, I saw the error like this:
```
[2016-07-05 02:25:34+0000] + perform_migration
[2016-07-05 02:25:34+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2016-07-05 02:25:34+0000] + chpst -u vcap:vcap bundle exec rake db:migrate
[2016-07-05 02:25:45+0000] rake aborted!
[2016-07-05 02:25:45+0000] Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: Connection refused
[2016-07-05 02:25:45+0000]      Is the server running on host "10.0.16.4" and accepting
[2016-07-05 02:25:45+0000]      TCP/IP connections on port 5524?
[2016-07-05 02:25:45+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:241:in `initialize'
[2016-07-05 02:25:45+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:241:in `new'
[2016-07-05 02:25:45+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/adapters/postgres.rb:241:in `connect'
```
Looks like cloud_controller_ng needs to connect to a real database in the step of 'pre-start' for migration, but on the same node postgres job won't be ready before all 'pre-start' steps are done. Does it mean that cf release won't support such a case of deploying all jobs on a single node anymore?

BTW, if we move postgres to another node, we can deploy the cf successfully. 

Thanks

**Comment by gossion** [comment]
And another question is: it is a new deployment, why it need to perform_migration? 
Thank you.

**Comment by SocalNick** [comment]
@gossion - fyi, we've moved this to the CAPI backlog: https://www.pivotaltracker.com/projects/966314

**Comment by Amit-PivotalLabs** [comment]
Closing issue as the story appears to be accepted.
