### ISSUE TITLE
api_worker_z1/0' is not running after update

### ISSUE THREAD

**Issue by Pratibha-28** [cloudfoundry/cf-release#1013]
I have been upgrading CF from v235 to v238 on AWS and something seems to have gone wrong with the cloud controller worker. The error is:

```
`api_worker_z1/0' is not running after update, `api_worker_z2/0' is not running after update
```

The logs suggest this:

```
Sequel::Migrator::NotCurrentError: migrator is not current.
```

And the process `cloud_controller_worker_1` is failing (Does not exist) on the `api_worker` VMs. In turn it has affected the `api_z1`, `api_z2` as well causing `cloud_controller_ng`, `cloud_controller_worker_local_1`, `cloud_controller_worker_local_2` processes to fail.

Below is content of `cloud_controller_worker_ctl.err.log`:

```
 ------------ STARTING cloud_controller_worker_ctl at Sat Jul 16 12:40:13 UTC 2016 --------------
 rake aborted!
Sequel::Migrator::NotCurrentError: migrator is not current
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/extensions/migration.rb:368:in `check_current'
/var/vcap/data/packages/cloud_controller_ng/b460066ea0bfd9d2106228a0f9c45dc228548787.1-840069fe82c7f7775c84fdffdf3d94a0ddabb44a/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:29:in `check_migrations!'
/var/vcap/data/packages/cloud_controller_ng/b460066ea0bfd9d2106228a0f9c45dc228548787.1-840069fe82c7f7775c84fdffdf3d94a0ddabb44a/cloud_controller_ng/lib/cloud_controller/db.rb:52:in `load_models'
/var/vcap/data/packages/cloud_controller_ng/b460066ea0bfd9d2106228a0f9c45dc228548787.1-840069fe82c7f7775c84fdffdf3d94a0ddabb44a/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:12:in `setup_environment'
/var/vcap/data/packages/cloud_controller_ng/b460066ea0bfd9d2106228a0f9c45dc228548787.1-840069fe82c7f7775c84fdffdf3d94a0ddabb44a/cloud_controller_ng/lib/tasks/jobs.rake:32:in `start_working'
```

Any way to recover from this?

**Comment by Amit-PivotalLabs** [comment]
ping @SocalNick @utako

**Comment by thausler786** [comment]
Hey @Pratibha-28,

What version of bosh are you using?  If you are using an older version of bosh, migrations will not run in v238 because bosh will not have the `spec.bootstrap` option available.  

If you have an older bosh version and go into your `pre-start.err.log` files you should find logging saying `Skipping migrations...` for all of your `api` and `cloud_controller_worker` vms. 

If you are on the latest bosh and you still get this problem, you can look in these same `pre-start.err.log` files to see if your migrations are indeed running or if they are erroring for some reason.

Best,

@thausler786 && @rizwanreza 
CAPI team members

**Comment by dsabeti** [comment]
Closing due to inactivity. Feel free to re-open the issue if you continue to see this problem.
