### ISSUE TITLE
bosh deploy fails while updating job blobstore_z1 > blobstore_z1/0

### ISSUE THREAD

**Issue by MoizArif** [cloudfoundry/cf-release#1020]
Hi all, 
I am deploying CF using BOSH and i am getting this error:

`Error 400007: 'blobstore_z1/0 (0eb27491-096c-4506-98b8-e06763d7f996)' is not running after update. Review logs for failed jobs: blobstore_nginx
`
Here is the log from bosh task:

```
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:113:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:111:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:110:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:105:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2016-07-28 22:29:47 #19665] [] ERROR -- DirectorJobRunner: Worker thread raised exception: 'blobstore_z1/0 (0eb27491-096c-4506-98b8-e06763d7f996)' is not running after update. Review logs for failed jobs: blobstore_nginx - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:113:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:111:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:110:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:105:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-07-28 22:29:47 #19665] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
```

Output of bosh vms command:

```
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs           |
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+
| api_z1/0 (c26b3732-7294-43d6-8eb7-e773dd84824f)                           | running | n/a | large_z1  | 10.10.0.104   |
| blobstore_z1/0 (0eb27491-096c-4506-98b8-e06763d7f996)                     | failing | n/a | medium_z1 | 10.10.0.102   |
| consul_z1/0 (517d10bf-637a-470f-97ac-48ecc5549e9c)                        | running | n/a | small_z1  | 10.10.0.137   |
| doppler_z1/0 (6c672830-e1c0-4998-8d20-06e29be5a733)                       | running | n/a | medium_z1 | 10.10.0.107   |
| etcd_z1/0 (28e6d628-5b77-4d3f-8882-865a377e9946)                          | running | n/a | medium_z1 | 10.10.0.133   |
| ha_proxy_z1/0 (77732d60-ac2e-4be0-bfa1-59ff5f75ce37)                      | running | n/a | router_z1 | 192.168.14.90 |
|                                                                           |         |     |           | 10.10.0.125   |
| hm9000_z1/0 (e2f9d941-e8a2-49cb-a3ed-59c8f8cecf30)                        | running | n/a | medium_z1 | 10.10.0.105   |
| loggregator_trafficcontroller_z1/0 (39ab5e4f-0a8a-4cbd-bc5d-25c35420a362) | running | n/a | small_z1  | 10.10.0.108   |
| nats_z1/0 (d5829968-5616-4d51-bb32-d5f906273aae)                          | running | n/a | medium_z1 | 10.10.0.127   |
| postgres_z1/0 (3065a829-4f96-433d-a76b-dcc1ecf30c03)                      | running | n/a | medium_z1 | 10.10.0.129   |
| router_z1/0 (b3c8d635-47ee-41e7-b38b-28690eb1167d)                        | running | n/a | router_z1 | 10.10.0.130   |
| runner_z1/0 (2fd481fa-dc8b-458c-8d68-ae9f7a542d71)                        | running | n/a | runner_z1 | 10.10.0.106   |
| stats_z1/0 (6279e637-7c4d-4355-8752-c6f45641dc2e)                         | running | n/a | small_z1  | 10.10.0.101   |
| uaa_z1/0 (17488c94-2fa5-4085-8f2f-54bf67ec5059)                           | running | n/a | medium_z1 | 10.10.0.103   |
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+
```

output of bosh instances --ps

```
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| Instance                                                                   | State   | AZ  | VM Type   | IPs           |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| api_z1/0 (c26b3732-7294-43d6-8eb7-e773dd84824f)*                           | running | n/a | large_z1  | 10.10.0.104   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| blobstore_z1/0 (0eb27491-096c-4506-98b8-e06763d7f996)*                     | failing | n/a | medium_z1 | 10.10.0.102   |
|   consul_agent                                                             | running |     |           |               |
|   metron_agent                                                             | running |     |           |               |
|   blobstore_nginx                                                          | unknown |     |           |               |
|   blobstore_url_signer                                                     | running |     |           |               |
|   route_registrar                                                          | running |     |           |               |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| consul_z1/0 (517d10bf-637a-470f-97ac-48ecc5549e9c)*                        | running | n/a | small_z1  | 10.10.0.137   |
|   consul_agent                                                             | running |     |           |               |
|   metron_agent                                                             | running |     |           |               |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| doppler_z1/0 (6c672830-e1c0-4998-8d20-06e29be5a733)*                       | running | n/a | medium_z1 | 10.10.0.107   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| etcd_z1/0 (28e6d628-5b77-4d3f-8882-865a377e9946)*                          | running | n/a | medium_z1 | 10.10.0.133   |
|   etcd                                                                     | running |     |           |               |
|   etcd_metrics_server                                                      | running |     |           |               |
|   metron_agent                                                             | running |     |           |               |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| ha_proxy_z1/0 (77732d60-ac2e-4be0-bfa1-59ff5f75ce37)*                      | running | n/a | router_z1 | 192.168.14.90 |
|                                                                            |         |     |           | 10.10.0.125   |
|   consul_template                                                          | running |     |           |               |
|   haproxy_config                                                           | running |     |           |               |
|   haproxy                                                                  | running |     |           |               |
|   metron_agent                                                             | running |     |           |               |
|   consul_agent                                                             | running |     |           |               |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| hm9000_z1/0 (e2f9d941-e8a2-49cb-a3ed-59c8f8cecf30)*                        | running | n/a | medium_z1 | 10.10.0.105   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| loggregator_trafficcontroller_z1/0 (39ab5e4f-0a8a-4cbd-bc5d-25c35420a362)* | running | n/a | small_z1  | 10.10.0.108   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| nats_z1/0 (d5829968-5616-4d51-bb32-d5f906273aae)*                          | running | n/a | medium_z1 | 10.10.0.127   |
|   nats                                                                     | running |     |           |               |
|   nats_stream_forwarder                                                    | running |     |           |               |
|   metron_agent                                                             | running |     |           |               |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| postgres_z1/0 (3065a829-4f96-433d-a76b-dcc1ecf30c03)*                      | running | n/a | medium_z1 | 10.10.0.129   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| router_z1/0 (b3c8d635-47ee-41e7-b38b-28690eb1167d)*                        | running | n/a | router_z1 | 10.10.0.130   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| runner_z1/0 (2fd481fa-dc8b-458c-8d68-ae9f7a542d71)*                        | running | n/a | runner_z1 | 10.10.0.106   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| stats_z1/0 (6279e637-7c4d-4355-8752-c6f45641dc2e)*                         | running | n/a | small_z1  | 10.10.0.101   |
|   collector                                                                | running |     |           |               |
|   metron_agent                                                             | running |     |           |               |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+
| uaa_z1/0 (17488c94-2fa5-4085-8f2f-54bf67ec5059)*                           | running | n/a | medium_z1 | 10.10.0.103   |
+----------------------------------------------------------------------------+---------+-----+-----------+---------------+

(*) Bootstrap node

Instances total: 14
```

From monit logs inside blobstore_z1/0 VM:

```
[UTC Jul 29 03:49:56] info     : 'blobstore_nginx' start: /var/vcap/jobs/blobstore/bin/nginx_ctl
[UTC Jul 29 03:49:58] error    : 'blobstore_nginx' failed to start
[UTC Jul 29 03:50:02] error    : 'blobstore_nginx' process is not running
[UTC Jul 29 03:50:02] info     : 'blobstore_nginx' trying to restart
```

and starting it manually gives:
`/var/vcap/jobs/blobstore/bin/nginx_ctl: line 15: /nginx.pid: Permission denied`

logs from /var/vcap/sys/log/blobstore/nginx.stderr.log
```
nginx: [emerg] bind() to 0.0.0.0:443 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:443 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:443 failed (13: Permission denied)
```

Can anyone help me with this issue?

**Comment by Amit-PivotalLabs** [comment]
ping @utako @SocalNick

**Comment by MoizArif** [comment]
Hi @utako and @SocalNick , any pointers on my issue?

**Comment by SocalNick** [comment]
@MoizArif what version of CF? In 239, we made it such that you have to run the blobstore on an unprivileged port, 4443 by default. Please see the release notes: https://github.com/cloudfoundry/cf-release/releases/tag/v239

**Comment by MoizArif** [comment]
Using release 239
```
root@node-42:~/cf-release# bosh releases
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'

+------+-------------+-------------+
| Name | Versions    | Commit Hash |
+------+-------------+-------------+
| cf   | 239+dev.26  | aae5794a    |
|      | 239+dev.27* | ea7c35cf    |
+------+-------------+-------------+
(*) Currently deployed

Releases total: 1
```

So i should change the tls port from 443 to 4443, right?

an excerpt from my existing cf-deployment.yml file:
```
properties:
  acceptance_tests: null
  app_domains:
  - cf-app.com
  app_ssh: null
  blobstore:
    admin_users:
    - password: xxx
      username: xxx
    port: 8080
    secure_link:
      secret: xxx
    tls:
      port: 443
```

**Comment by MoizArif** [comment]
Okay i have understood it from the release specs. I changed the tls port to 4443 (above 1024) and i am now able to get pass the error mentioned in this issue. 

Wow, thanks a bunch @SocalNick.

**Comment by MoizArif** [comment]
Are there any changes to api section as well? Now my api_z1/0 got stuck.

```
  Started updating job api_z1 > api_z1/0 (d67835fc-9b8c-4652-9f20-4392f5238a52) (canary). Failed: Action Failed get_task: Task 51780263-1710-4fa2-5d4d-f4516fb1c5b9 result: 1 of 3 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: cloud_controller_clock, cloud_controller_worker. (00:04:22)

Error 450001: Action Failed get_task: Task 51780263-1710-4fa2-5d4d-f4516fb1c5b9 result: 1 of 3 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: cloud_controller_clock, cloud_controller_worker.
```

bosh instances --ps
```
+----------------------------------------------------------------------------+---------+-----+-----------
+---------------+
| Instance                                                                   | State   | AZ  | VM Type   
| IPs           |
+----------------------------------------------------------------------------+---------+-----+-----------
+---------------+
| api_z1/0 (d67835fc-9b8c-4652-9f20-4392f5238a52)*                           | stopped | n/a | large_z1  
| 10.10.0.104   |
+----------------------------------------------------------------------------+---------+-----+-----------
+---------------+
```

**Comment by SocalNick** [comment]
Check the log files by `bosh ssh api_z1/0`. The log file you should look at are `/var/vcap/sys/log/cloud_controller_ng/pre-start.stderr.log` and `/var/vcap/sys/log/cloud_controller_ng/pre-start.stdout.log`.

**Comment by MoizArif** [comment]
@SocalNick , The error is:

```
  Started updating job api_z1 > api_z1/0 (4f30c066-9b5d-4ab9-b0b4-6f3a3170027a) (canary). Failed: Action Failed get_task: Task 48b059c1-2832-4053-43b4-5f4b12833847 result: 1 of 2 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: consul_agent. (00:11:03)

Error 450001: Action Failed get_task: Task 48b059c1-2832-4053-43b4-5f4b12833847 result: 1 of 2 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: consul_agent
```

Output of pre-start.stdout.log:

```
[2016-07-30 20:30:14+0000] {"timestamp":1469910614.5912402,"message":"PG::UndefinedTable: ERROR:  relation \"schema_migrations\" does not exist\nLINE 1: SELECT NULL AS \"nil\" FROM \"schema_migrations\" LIMIT 1\n                                  ^: SELECT NULL AS \"nil\" FROM \"schema_migrations\" LIMIT 1","log_level":"error","source":"cc.db.migrations","data":{},"thread_id":47063367889160,"fiber_id":47063403522820,"process_id":4702,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
[2016-07-30 20:30:14+0000] {"timestamp":1469910614.6184585,"message":"PG::UndefinedTable: ERROR:  relation \"schema_info\" does not exist\nLINE 1: SELECT NULL AS \"nil\" FROM \"schema_info\" LIMIT 1\n                                  ^: SELECT NULL AS \"nil\" FROM \"schema_info\" LIMIT 1","log_level":"error","source":"cc.db.migrations","data":{},"thread_id":47063367889160,"fiber_id":47063403522820,"process_id":4702,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
[2016-07-30 20:30:14+0000] {"timestamp":1469910614.6369526,"message":"PG::UndefinedTable: ERROR:  relation \"services\" does not exist\nLINE 1: ...\".\"attnum\" > 0) AND (\"pg_class\".\"oid\" = CAST(CAST('\"services...\n                                                             ^: SELECT \"pg_attribute\".\"attname\" AS \"name\", CAST(\"pg_attribute\".\"atttypid\" AS integer) AS \"oid\", CAST(\"basetype\".\"oid\" AS integer) AS \"base_oid\", format_type(\"basetype\".\"oid\", \"pg_type\".\"typtypmod\") AS \"db_base_type\", format_type(\"pg_type\".\"oid\", \"pg_attribute\".\"atttypmod\") AS \"db_type\", pg_get_expr(\"pg_attrdef\".\"adbin\", \"pg_class\".\"oid\") AS \"default\", NOT \"pg_attribute\".\"attnotnull\" AS \"allow_null\", COALESCE((\"pg_attribute\".\"attnum\" = ANY(\"pg_index\".\"indkey\")), false) AS \"primary_key\" FROM \"pg_class\" INNER JOIN \"pg_attribute\" ON (\"pg_attribute\".\"attrelid\" = \"pg_class\".\"oid\") INNER JOIN \"pg_type\" ON (\"pg_type\".\"oid\" = \"pg_attribute\".\"atttypid\") LEFT OUTER JOIN \"pg_type\" AS \"basetype\" ON (\"basetype\".\"oid\" = \"pg_type\".\"typbasetype\") LEFT OUTER JOIN \"pg_attrdef\" ON ((\"pg_attrdef\".\"adrelid\" = \"pg_class\".\"oid\") AND (\"pg_attrdef\".\"adnum\" = \"pg_attribute\".\"attnum\")) LEFT OUTER JOIN \"pg_index\" ON ((\"pg_index\".\"indrelid\" = \"pg_class\".\"oid\") AND (\"pg_index\".\"indisprimary\" IS TRUE)) WHERE ((\"pg_attribute\".\"attisdropped\" IS FALSE) AND (\"pg_attribute\".\"attnum\" > 0) AND (\"pg_class\".\"oid\" = CAST(CAST('\"services\"' AS regclass) AS oid))) ORDER BY \"pg_attribute\".\"attnum\"","log_level":"error","source":"cc.db.migrations","data":{},"thread_id":47063367889160,"fiber_id":47063403522820,"process_id":4702,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
[2016-07-30 20:30:14+0000] {"timestamp":1469910614.6378853,"message":"PG::UndefinedTable: ERROR:  relation \"services\" does not exist\nLINE 1: SELECT * FROM \"services\" LIMIT 1\n                      ^: SELECT * FROM \"services\" LIMIT 1","log_level":"error","source":"cc.db.migrations","data":{},"thread_id":47063367889160,"fiber_id":47063403522820,"process_id":4702,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
[2016-07-30 20:30:14+0000] {"timestamp":1469910614.6610012,"message":"Begin applying migration 20130131184954_new_initial_schema.rb, direction: up","log_level":"info","source":"cc.db.migrations","data":{},"thread_id":47063367889160,"fiber_id":47063403522820,"process_id":4702,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
[2016-07-30 20:30:15+0000] {"timestamp":1469910615.5097067,"message":"Finished applying migration 20130131184954_new_initial_schema.rb, direction: up, took 0.848662 seconds","log_level":"info","source":"cc.db.migrations","data":{},"thread_id":47063367889160,"fiber_id":47063403522820,"process_id":4702,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
```

Output of pre-start.stderr.log:

```
[2016-07-30 20:30:12+0000] + mkdir -p /var/vcap/data/nginx_cc/tmp
[2016-07-30 20:30:12+0000] + chown vcap:vcap /var/vcap/data/nginx_cc/tmp
[2016-07-30 20:30:12+0000] + mkdir -p /var/vcap/packages/nginx/proxy_temp
[2016-07-30 20:30:12+0000] + touch /var/vcap/packages/nginx/logs/error.log
[2016-07-30 20:30:12+0000] + chown vcap:vcap /var/vcap/packages/nginx/logs/error.log
[2016-07-30 20:30:12+0000] + mkdir -p /var/vcap/data/cloud_controller_ng/diagnostics
[2016-07-30 20:30:12+0000] + chown vcap:vcap /var/vcap/data/cloud_controller_ng/diagnostics
[2016-07-30 20:30:12+0000] + deny_overlapping_app_and_system_domains
[2016-07-30 20:30:12+0000] + app_domains=cf-app.com
[2016-07-30 20:30:12+0000] + system_domain=domain
[2016-07-30 20:30:12+0000] + ruby /var/vcap/jobs/cloud_controller_ng/bin/check_for_domain_overlap.rb domain cf-app.com
[2016-07-30 20:30:12+0000] + overlap_result=0
[2016-07-30 20:30:12+0000] + [[ 0 -ne 0 ]]
[2016-07-30 20:30:12+0000] + perform_migration
[2016-07-30 20:30:12+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2016-07-30 20:30:12+0000] + chpst -u vcap:vcap bundle exec rake db:migrate
[2016-07-30 20:30:22+0000] + result=0
[2016-07-30 20:30:22+0000] + [[ 0 -ne 0 ]]
[2016-07-30 20:30:22+0000] + popd
[2016-07-30 20:30:22+0000] + seed_db
[2016-07-30 20:30:22+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2016-07-30 20:30:22+0000] + chpst -u vcap:vcap bundle exec rake db:seed
[2016-07-30 20:30:24+0000] rake aborted!
[2016-07-30 20:30:24+0000] Sequel::ValidationFailed: name can contain multiple subdomains, each having only alphanumeric characters and hyphens of up to 63 characters, see RFC 1035.
[2016-07-30 20:30:24+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/model/base.rb:1543:in `save'
[2016-07-30 20:30:24+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/model/base.rb:148:in `create'
[2016-07-30 20:30:24+0000] /var/vcap/data/packages/cloud_controller_ng/cf72e41bf598298829d239e3e96cf50cf8417c2e.1-1971c5c8781e8b7c3bbf23ce0e04a6033aca2dfd/cloud_controller_ng/lib/cloud_controller/seeds.rb:86:in `create_seed_domains'
[2016-07-30 20:30:24+0000] /var/vcap/data/packages/cloud_controller_ng/cf72e41bf598298829d239e3e96cf50cf8417c2e.1-1971c5c8781e8b7c3bbf23ce0e04a6033aca2dfd/cloud_controller_ng/lib/cloud_controller/seeds.rb:9:in `write_seed_data'
[2016-07-30 20:30:24+0000] /var/vcap/data/packages/cloud_controller_ng/cf72e41bf598298829d239e3e96cf50cf8417c2e.1-1971c5c8781e8b7c3bbf23ce0e04a6033aca2dfd/cloud_controller_ng/lib/tasks/db.rake:135:in `block (3 levels) in <top (required)>'
[2016-07-30 20:30:24+0000] /var/vcap/data/packages/cloud_controller_ng/cf72e41bf598298829d239e3e96cf50cf8417c2e.1-1971c5c8781e8b7c3bbf23ce0e04a6033aca2dfd/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:39:in `setup_environment'
[2016-07-30 20:30:24+0000] /var/vcap/data/packages/cloud_controller_ng/cf72e41bf598298829d239e3e96cf50cf8417c2e.1-1971c5c8781e8b7c3bbf23ce0e04a6033aca2dfd/cloud_controller_ng/lib/tasks/db.rake:134:in `block (2 levels) in <top (required)>'
[2016-07-30 20:30:24+0000] Tasks: TOP => db:seed
[2016-07-30 20:30:24+0000] (See full trace by running task with --trace)
```

**Comment by SocalNick** [comment]
@MoizArif it appears to be a configuration error with your system domain, do you have it set to `domain`? How are you generating your deployment manifest? Your system and app domains should be something like:

```
system_domain: system.some-domain.com
system_domain_organization: system
app_domains:
  - apps.some-domain.com
```

or you can use the same apps and system domain

```
system_domain: some-domain.com
app_domains:
  - some-domain.com
```

If you are still having issues, our working hours are M-F 9a-6p PT. We have a dedicated interrupt pair available to help in [our slack channel](https://cloudfoundry.slack.com/messages/capi/), drop by and you can get some realtime help.

cc @utako

**Comment by MoizArif** [comment]
@SocalNick , yes i am actually using domain.

```
  system_domain: domain
  system_domain_organization: domain.org
```

i am using the this to generate the deployment manifest:

`./scripts/generate_deployment_manifest openstack /root/my-bosh/cf-stub.yml > cf-deployment.yml`

Let me change the  domain names like you suggested and try again.
Do "some-domain.com" needs to be routable ?

**Comment by SocalNick** [comment]
Yes, you need to be able to set a wildcard record for the domain you use. Please follow the [instructions for Preparing to Deploy on OpenStack](http://docs.cloudfoundry.org/deploying/openstack/index.html).

**Comment by MoizArif** [comment]
Using the proper domain name worked for me at this point. Now running into another issue:

```
  Started updating job runner_z1 > runner_z1/0 (13743010-281b-4601-b117-479472016342) (canary). Failed: 'runner_z1/0 (13743010-281b-4601-b117-479472016342)' is not running after update. Review logs for failed jobs: warden, dea_next (00:11:00)

Error 400007: 'runner_z1/0 (13743010-281b-4601-b117-479472016342)' is not running after update. Review logs for failed jobs: warden, dea_next
```

All processes on the runner_z1/0 vm are running:
```
root@79c4cc9f-6b6d-49d4-819d-77048cbfd1a1:/home/vcap# monit summary
The Monit daemon 5.2.5 uptime: 20m 

Process 'consul_agent'              running
Process 'warden'                    running
Process 'dea_next'                  running
Process 'dir_server'                running
Process 'dea_logging_agent'         running
Process 'metron_agent'              running
System 'system_localhost'           running
```

The warden error logs report, /var/vcap/sys/log/warden_ctl.err.log:
```
[2016-07-30 22:37:00+0000] ------------ STARTING warden_ctl at Sat Jul 30 22:37:00 UTC 2016 --------------
[2016-07-30 22:38:14+0000] rake aborted!
[2016-07-30 22:38:14+0000] Warden::WardenError: command exited with failure
[2016-07-30 22:38:14+0000] Tasks: TOP => warden:start
[2016-07-30 22:38:14+0000] (See full trace by running task with --trace)
[2016-07-30 22:38:14+0000] rake aborted!
[2016-07-30 22:38:14+0000] rake aborted!
[2016-07-30 22:38:14+0000] no acceptor (port is in use or requires root privileges)
[2016-07-30 22:38:14+0000] rake aborted!
[2016-07-30 22:38:14+0000] no acceptor (port is in use or requires root privileges)
[2016-07-30 22:38:14+0000] no acceptor (port is in use or requires root privileges)
[2016-07-30 22:38:14+0000] Tasks: TOP => warden:start
[2016-07-30 22:38:14+0000] (See full trace by running task with --trace)
```

/var/vcap/sys/log/dea_ctl.err.log reports:
```
[2016-07-30 22:25:47+0000] ------------ STARTING dea_ctl at Sat Jul 30 22:25:47 UTC 2016 --------------
[2016-07-30 22:25:48+0000] /var/vcap/jobs/dea_next/bin/dea_ctl: line 69: /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory
[2016-07-30 22:27:56+0000] ------------ STARTING dea_ctl at Sat Jul 30 22:27:56 UTC 2016 --------------
[2016-07-30 22:30:10+0000] ------------ STARTING dea_ctl at Sat Jul 30 22:30:10 UTC 2016 --------------
[2016-07-30 22:32:24+0000] ------------ STARTING dea_ctl at Sat Jul 30 22:32:24 UTC 2016 --------------

```

**Comment by MoizArif** [comment]
@SocalNick : 
Another quick question, the domain should point to CF router IP ?

**Comment by jleavers** [comment]
You would normally point this at the loadbalancer, in your case this looks to be the ha_proxy_z1 VM - although you could also use an external loadbalancer instead - which then forwards traffic onto the routers.

**Comment by MoizArif** [comment]
@jleavers , thanks for the reply. in case my system_domain name is cf.test.com ,  i do:

`cf api --skip-ssl-validation http://cf.test.com`

with cf.test.com pointing to the Floating IP assigned to ha_proxy_z1 VM and it throws out:

```
Setting api endpoint to cf.test.com...
FAILED
Server error, status code: 503, error code: 0, message:
```

What do you think might be the issue here?

**Comment by jleavers** [comment]
Normally the API URL will be api.SYSTEM_DOMAIN, e.g. api.cf.test.com in your example. You will probably see this listed in your deployment manifest.

**Comment by MoizArif** [comment]
@jleavers : i have used the following command:

`cf api --skip-ssl-validation api.cf.test.com`

and still getting the same error message:

```
root@dns-vm:/home/ubuntu# ./cf api --skip-ssl-validation api.cf.test.com
Setting api endpoint to http://api.cf.test.com...
FAILED
Server error, status code: 503, error code: 0, message:
```

DNS query results in:

```
root@dns-vm:/home/ubuntu# nslookup api.cf.test.com
Server:         192.168.14.89
Address:        192.168.14.89#53

Name:   api.cf.test.com
Address: 192.168.14.90
```
and the DNS entry is: `*.cf.test.com.        IN      A       192.168.14.90`
where 192.168.14.90 is the Floating IP of the ha_proxy_z1/0 VM.

**Comment by SocalNick** [comment]
@MoizArif you are likely going to have to start looking at logs for all the components involved. That would be HAProxy, Gorouter, and CloudController. I'm going to close this issue because your original issue has been resolved. I encourage you to investigate your deployment thoroughly and try to determine the proper team to contact for more help. As I mentioned, you might be able to get help in realtime in the [CloudFoundry OSS Slack](https://cloudfoundry.slack.com/messages/general/). Most teams have interrupt pairs willing to help debug community issues.

**Comment by MoizArif** [comment]
@SocalNick , i dont have access to CF slack channel. can you send me an invite?

**Comment by MoizArif** [comment]
@SocalNick , yes i am doing exactly that. Thanks for all the help :)
