### ISSUE TITLE
UAA fail during deployment CF v251

### ISSUE THREAD

**Issue by kapekto1** [cloudfoundry/cf-release#1141]
Hello.
I have a problem deploying CF in AWS environment. Below you will find evidences of this error.
If someone can give me any hint how to get rid of this error I will be grateful...

**bosh -n deploy**
```
Started updating instance uaa_z1 > uaa_z1/a5376cd4-6033-42a8-a67b-c3f073e78e7d (0) (canary). Failed: Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa. (00:01:04)

Error 450001: Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.
```

**bosh task 79 --debug**
```
D, [2017-01-20 22:35:07 #2843] [] DEBUG -- DirectorJobRunner: RECEIVED: director.d38c3ec5-f201-48c4-b8ed-79acf336d0ea.b77b515d-d981-4ba4-beb0-5f39f669a57b {"exception":{"message":"Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa."}}
E, [2017-01-20 22:35:07 #2843] [canary_update(uaa_z1/a5376cd4-6033-42a8-a67b-c3f073e78e7d (0))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.>
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:247:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:302:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:55:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:357:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:166:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:321:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:132:in `run_script'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/state_applier.rb:51:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:112:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:110:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:109:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:104:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2017-01-20 22:35:07 #2843] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa. - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:247:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:302:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:55:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:357:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:166:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:321:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:132:in `run_script'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/state_applier.rb:51:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:112:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:110:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:109:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:104:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-01-20 22:35:07 #2843] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.003448s) SELECT NULL
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000429s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON ("deployments_stemcells"."stemcell_id" = "stemcells"."id") WHERE ("deployments_stemcells"."deployment_id" = 2)
D, [2017-01-20 22:35:07 #2843] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000189s) SELECT NULL
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000173s) SELECT NULL
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000102s) SELECT NULL
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.001249s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:tk-aws-cf') AND ("uid" = '7766e5bc-2586-47df-85e8-ecf3e6700561'))
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:tk-aws-cf uid: 7766e5bc-2586-47df-85e8-ecf3e6700561
I, [2017-01-20 22:35:07 #2843] [task:79]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"46e127e3-1c60-44cc-bb00-07faa645775d","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'tk-aws-cf' against Director '44cae4dd-3f5a-41b2-b323-cff763cef514': #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.>","created_at":1484951707}
E, [2017-01-20 22:35:07 #2843] [task:79] ERROR -- DirectorJobRunner: Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:247:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:302:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:55:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:357:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:166:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:321:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/agent_client.rb:132:in `run_script'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/state_applier.rb:51:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:112:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:110:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:109:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0000/lib/bosh/director/job_updater.rb:104:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0000/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000147s) SELECT NULL
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000099s) BEGIN
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.000283s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-01-20 22:35:07.283450+0000', "description" = 'create deployment', "result" = 'Action Failed get_task: Task 53ed193e-7aef-4085-7ffd-25e8f404d96b result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.', "output" = '/var/vcap/store/director/tasks/79', "checkpoint_time" = '2017-01-20 22:33:57.272167+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'tk-aws-cf', "started_at" = '2017-01-20 22:33:57.272113+0000' WHERE ("id" = 79)
D, [2017-01-20 22:35:07 #2843] [task:79] DEBUG -- DirectorJobRunner: (0.011345s) COMMIT
I, [2017-01-20 22:35:07 #2843] []  INFO -- DirectorJobRunner: Task took 1 minute 10.026260698000002 seconds to process.
```

**bosh instances --ps**

```
+----------------------------------------------------------------------------+---------+-----+-----------+-------------+
| uaa_z1/0 (a5376cd4-6033-42a8-a67b-c3f073e78e7d)*                           | failing | n/a | medium_z1 | 10.11.0.102 |
|   consul_agent                                                             | running |     |           |             |
|   uaa                                                                      | failing |     |           |             |
|   metron_agent                                                             | running |     |           |             |
|   route_registrar                                                          | running |     |           |             |
|   statsd-injector                                                          | running |     |           |             |
+----------------------------------------------------------------------------+---------+-----+-----------+-------------+
```

**uaa_z1/a5376cd4-6033-42a8-a67b-c3f073e78e7d:/var/vcap/sys/log/uaa# cat post-start.stdout.log**
```
uaa-post-start - starting at Fri Jan 20 14:41:59 UTC 2017
uaa-post-start - performing post start healthcheck until 2017-01-20 14:51:59.444974334
uaa-post-start - post start failed - server failed to start successfully at Fri Jan 20 14:42:03 UTC 2017
uaa-post-start - cleaned up timestamp files
uaa-post-start - starting at Fri Jan 20 17:35:17 UTC 2017
uaa-post-start - performing post start healthcheck until 2017-01-20 17:45:17.087310349
uaa-post-start - post start failed - server failed to start successfully at Fri Jan 20 17:35:19 UTC 2017
uaa-post-start - cleaned up timestamp files
uaa-post-start - starting at Fri Jan 20 20:27:59 UTC 2017
uaa-post-start - performing post start healthcheck until 2017-01-20 20:37:59.672345095
uaa-post-start - post start failed - server failed to start successfully at Fri Jan 20 20:27:59 UTC 2017
uaa-post-start - cleaned up timestamp files
uaa-post-start - starting at Fri Jan 20 22:35:03 UTC 2017
uaa-post-start - performing post start healthcheck until 2017-01-20 22:45:03.293068695
uaa-post-start - post start failed - server failed to start successfully at Fri Jan 20 22:35:06 UTC 2017
uaa-post-start - cleaned up timestamp files

```

**uaa.log entry:**

```
[2017-01-20 14:42:00.926] uaa - 9891 [localhost-startStop-1] .... ERROR --- DispatcherServlet: Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"
```

**Comment by dsabeti** [comment]
@kapekto1 My guess is that you're missing a manifest property. Do you have a value set for `login.saml.serviceProviderKey` in your manifest? If you need help finding it, could you provide your deployment manifest **with any sensitive information, such as passwords and private keys, redacted**?

**Comment by harshalk91** [comment]
@dsabeti I am having exactly same issue and i am using release `cf-250`
Attaching redacted yml.
[cf_redacted.txt](https://github.com/cloudfoundry/cf-release/files/728872/cf_redacted.txt)

**Comment by StBurcher** [comment]
I have the same Issue also with CF-250 on Openstack Liberty

**Comment by harshalk91** [comment]
I am using openstack mitaka.

**Comment by kapekto1** [comment]
Hello, yes, it was it. I used [http://docs.cloudfoundry.org/deploying/aws/cf-stub.html#example-stub] a stub file.

```
 saml:
      serviceProviderKeyPassword: "<redacted>"
```

is not present there.
Thanks for help!

**Comment by dsabeti** [comment]
@kapekto1 I'll make sure the stub file on that web page gets updated to include `same.serviceProviderKeyPassword`.

**Comment by StBurcher** [comment]
Works now also in my environment.  Thank you
