### ISSUE TITLE
cf push fails when updating an existing app and the stack is specified

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cf-release#1174]
## Issue
cf push fails under these circumstances:
  1) the application already exists
  2) the stack was specified
  3) the number of instances is changed (could be other properties also)

## Steps to Reproduce
1) cf push apptest -p c:\temp\assets\staticfile\ -s cflinuxfs2 -b staticfile_buildpack -i 1
```
Using stack cflinuxfs2...
OK
...normal push stuff...
#0   running   2017-03-22 03:48:36 PM   0.0%   3.6M of 256M   6.1M of 512M
```
2) cf push apptest -p c:\temp\assets\staticfile\ -s cflinuxfs2 -b staticfile_buildpack -i 2
```
Using stack cflinuxfs2...
OK
Updating app apptest in org jmprice / space Test as jmprice...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

## Error in cloud_controller_ng.log
```
{"timestamp":1490219515.547693,
"message":"Request failed: 500: {\"code\"=>10001,
 \"description\"=>\"undefined method `droplet_hash' for nil:NilClass\",
 \"error_code\"=>\"CF-NoMethodError\",
 \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/buildpack/lifecycle_protocol.rb:58:in `desired_app_message'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/protocol.rb:72:in `desire_app_message'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/protocol.rb:42:in `desire_app_request'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/messenger.rb:40:in `send_desire_request'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:15:in `block in scale'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:40:in `with_logging'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:15:in `scale'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/app_observer.rb:42:in `react_to_instances_change'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/app_observer.rb:25:in `block in updated'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/app_observer.rb:46:in `with_diego_communication_handling'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/app_observer.rb:21:in `updated'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/models/runtime/app.rb:536:in `after_commit'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2076:in `block in _save'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:391:in `each'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:391:in `remove_transaction'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:238:in `_transaction'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/v2/app_update.rb:12:in `update'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/app/controllers/runtime/apps_controller.rb:242:in `update'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/app/controllers/base/base_controller.rb:80:in `dispatch'\",
 \"/var/vcap/data/packages/cloud_controller_ng/af2626cc79fbb1e3da1883ad80587ff3e6668531.1-8e625f7cf224f674b836155d0ba860b1470ee9a2/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `block in compile!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sinatra.rb:139:in `route_eval_with_newrelic'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sinatra.rb:119:in `process_route_with_newrelic'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sinatra.rb:164:in `dispatch_and_notice_errors_with_newrelic'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sinatra.rb:150:in `block in dispatch_with_newrelic'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sinatra.rb:147:in `dispatch_with_newrelic'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/new_relic_custom_attributes.rb:12:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/vcap_request_id.rb:14:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:47:in `call_app'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:12:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'\",
 \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}",
"log_level":"error",
"source":"cc.api",
"data":{"request_guid":"d837441c-29a5-479b-7989-aae3787ab114::9cb79e3e-8328-4430-be97-dfdd8104cb20"},
"thread_id":47457740159640,
"fiber_id":70012966577780,
"process_id":31603,
"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb",
"lineno":53,
"method":"block in registered"}
```

## Environment Info
cf-release v250
cf-cli - tested on multiple versions 6.18 - 6.25 (Linux and Windows)

**Jon Price
Intel Corporation**

**Comment by dsabeti** [comment]
Hey there @jmprice. I tried to reproduce this error but wasn't able to.

The error message seems to indicate that there's something wrong with the droplet -- specifically, that the Cloud Controller can't find the "current droplet" associated with the app.

I'm going to loop in @zrob and @Gerg who work on this component and will be better able to help you out.

**Comment by jmprice** [comment]
Hi @dsabeti, @zrob, and @Gerg,

I thought the same thing initially as well, but I am able to reproduce this in all of our different CF deployment environments which seems to rule out an issue with a specific droplet.

Could it have something to do with the fact that we do have more than one stack available?  We also have the windows2012R2 stack.

**Comment by ljfranklin** [comment]
@jmprice This should be fixed in v254 of cf-release. It seems like what you're seeing matches [this bug](https://www.pivotaltracker.com/story/show/137132839). The resolution to that bug was to return clearer error messages, and the actual underlying problem was solved as part of [this bug](https://www.pivotaltracker.com/story/show/137812701).

We're closing this out, but feel free to reopen if you're still seeing this problem after v254.

Thanks,
@ljfranklin and @jenspinney
