### ISSUE TITLE
Error 450001: Action Failed get_task: Task XXXX result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.

### ISSUE THREAD

**Issue by Senthilannaswamy** [cloudfoundry/cf-release#1176]
Hi All,

I'm trying to deploy CF on AWS following the link.
http://docs.cloudfoundry.org/deploying/aws/setup_bosh_aws.html

Please note, we trying to deploy on different IP range (10.11.x.x), with a bit of ruby code to update the IP, subnet name, security group name, RDS name and ELB. I was able to complete the "bosh aws create", successfully.

Regarding cf-stub manifest, Login saml - set with the key pair generated using generate-uaa-certs.sh

In cf-deployment, 
1. api_z1 .templates - update with the following 
  - name: consul_agent
    release: cf
2. blobstore - added the properties to deploy the VM for blobstore

While "bosh deploy", I'm getting error stating

> Started updating instance api_z1 > api_z1/82ff7a83-5344-49d9-9a4a-faf068a564d6 (0) (canary). Failed: Action Failed get_task: Task 74aeb2da-0e6b-45a2-6338-d0499189ebf5 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng. (00:05:12)
> 
> Error 450001: Action Failed get_task: Task 74aeb2da-0e6b-45a2-6338-d0499189ebf5 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.

Log from api_z1
api_z1/82ff7a83-5344-49d9-9a4a-faf068a564d6:/var/vcap/sys/log/cloud_controller_ng$ tail -f post-start.stderr.log

> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:59:in `run_canary'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:42:in `install'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/tasks/buildpacks.rake:7:in `block (3 levels) in <top (required)>'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:39:in `setup_environment'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/tasks/buildpacks.rake:6:in `block (2 levels) in <top (required)>'
> [2017-03-30 05:35:54+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'

Please let me know where I'm making mistake.

[cf-deployment - Copy.txt](https://github.com/cloudfoundry/cf-release/files/881378/cf-deployment.-.Copy.txt)
[cf-stub - Copy.txt](https://github.com/cloudfoundry/cf-release/files/881379/cf-stub.-.Copy.txt)

**Comment by dsabeti** [comment]
Hi @Senthilannaswamy. It looks like you didn't capture the whole stack trace from post-start.stderr.log. Could you try to find the actual exception that was raised? It typically looks something like this:
```
/tmp/script.rb:6:in `baz': This is the error message (ThisIsTheExceptionType) # <==== Look here
	from /tmp/script.rb:11:in `bar'
	from /tmp/script.rb:15:in `foo'
	from /tmp/script.rb:18:in `<main>'
```

**Comment by Senthilannaswamy** [comment]
Hi Dsabeti,

Please find the complete log...

> [2017-04-01 17:44:43+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `load'
[2017-04-01 17:44:43+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `<main>'
[2017-04-01 17:44:43+0000] Excon::Error::Timeout: connect_write timeout reached
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:267:in `select_with_timeout'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:131:in `rescue in block in connect'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:112:in `block in connect'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:103:in `each'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:103:in `connect'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/ssl_socket.rb:153:in `connect'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/socket.rb:29:in `initialize'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/ssl_socket.rb:9:in `initialize'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:403:in `new'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:403:in `socket'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:100:in `request_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/mock.rb:48:in `request_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:16:in `request_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:16:in `request_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:16:in `request_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:249:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/idempotent.rb:27:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:11:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:11:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:272:in `rescue in request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:215:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/idempotent.rb:27:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:11:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:11:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:272:in `rescue in request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:215:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/idempotent.rb:27:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:11:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:11:in `error_call'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:272:in `rescue in request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:215:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-aws-1.1.0/lib/fog/aws/storage.rb:612:in `_request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-aws-1.1.0/lib/fog/aws/storage.rb:607:in `request'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-aws-1.1.0/lib/fog/aws/requests/storage/get_bucket.rb:43:in `get_bucket'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-aws-1.1.0/lib/fog/aws/models/storage/directories.rb:21:in `get'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/directory.rb:16:in `get'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/idempotent_directory.rb:10:in `get_or_create'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:184:in `dir'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:134:in `files'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:70:in `block in cp_to_blobstore'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:57:in `open'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:57:in `cp_to_blobstore'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:46:in `block in cp_to_blobstore'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:126:in `with_retries'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:40:in `cp_to_blobstore'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:49:in `block in cp_to_blobstore'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:55:in `error_handling'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:49:in `cp_to_blobstore'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:20:in `upload_buildpack'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb:27:in `perform'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:59:in `run_canary'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:42:in `install'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/tasks/buildpacks.rake:7:in `block (3 levels) in <top (required)>'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:39:in `setup_environment'
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/tasks/buildpacks.rake:6:in `block (2 levels) in <top (required)>'
[2017-04-01 17:44:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[2017-04-01 17:44:43+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `load'
[2017-04-01 17:44:43+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `<main>'
[2017-04-01 17:44:43+0000] IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block

**Comment by dsabeti** [comment]
Ok, @Senthilannaswamy. It looks like there's an issue communicating with the blobstore:
```
[2017-04-01 17:44:43+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/directory.rb:16:in `get'
```
That's the Cloud Controller trying to fetch a blob from the blobstore.

The specific error is that its attempt to connect to the blobstore is timing out:
```
[2017-04-01 17:44:43+0000] Excon::Error::Timeout: connect_write timeout reached
```

As the deployer, you can configure the Cloud Controller to talk to a particular blobstore in these two sections: [here](https://github.com/cloudfoundry/cf-release/blob/faec81ce6e861daa507a720db77af302df81999d/templates/cf.yml#L896-L902) and [here](https://github.com/cloudfoundry/cf-release/blob/faec81ce6e861daa507a720db77af302df81999d/templates/cf.yml#L857-L882). Most likely, they have the same configuration.

If they're configured to use the local webdav, make sure that you're actually deploying one. If so, you'd see a job called `blobstore_z1` in the output of `bosh vms`.

Since you're using AWS, it's also quite possible that you're using s3 as your blobstore instead. If so, make sure your s3 urls and credentials are correct.

**Comment by Senthilannaswamy** [comment]
HI Dsabeti,

Agreed, please note we have given the access being provided and still getting the same error. I'm not sure want I'm missing here.

> +++ logger -p user.error -t vcap.cloud_controller_ng.post-start.stderr
[2017-04-04 16:05:04+0000] + main
[2017-04-04 16:05:04+0000] + install_buildpacks
[2017-04-04 16:05:04+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2017-04-04 16:05:04+0000] + chpst -u vcap:vcap bundle exec rake buildpacks:install
[2017-04-04 16:09:08+0000] rake aborted!
[2017-04-04 16:09:08+0000] CloudController::Blobstore::BlobstoreError: connect_write timeout reached
[2017-04-04 16:09:08+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:57:in `rescue in error_handling'
[2017-04-04 16:09:08+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:55:in `error_handling'
[2017-04-04 16:09:08+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:49:in `cp_to_blobstore'
[2017-04-04 16:09:08+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:20:in `upload_buildpack'
[2017-04-04 16:09:08+0000] /var/vcap/data/packages/cloud_controller_ng/eab4556f506c2363d80551ee6530b5cc301b726f/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb:27:in `perform'
"post-start.stderr.log" 475 lines, 81773 characters

**Comment by dsabeti** [comment]
@Senthilannaswamy, which blobstore are you using? How is the Cloud Controller configured to access it -- what do you actually have in your manifest? (Make sure to redact any credentials like passwords or private keys.)

**Comment by Senthilannaswamy** [comment]
HI Dsabeti,

I'm using following S3 bucket as the blobstore, with  "blobstore_type: fog" and configured with the  correct "aws_access_key_id/aws_secret_access_key" (which is the same keys used in other properties).
These are S3 configured,
1. sys-offshore-magellancloud-com-cc-buildpacks
2. sys-offshore-magellancloud-com
3. sys-offshore-magellancloud-com-cc-packages
4.sys-offshore-magellancloud-com-cc-resources
[cf-deployment_copy.txt](https://github.com/cloudfoundry/cf-release/files/894694/cf-deployment_copy.txt)

Please find the deployment manifest file attached.

Thanks
Senthil.

**Comment by dsabeti** [comment]
@Senthilannaswamy. It's unlikely that the credentials are the issue: notice that the error message says that the connection timed out. That means there's something missing in your networking configuration.

A few things you might consider:
1. Can you access this bucket at all? For example, can you use [s3cmd](http://s3tools.org/s3cmd) to access the bucket from your workstation. If not, there's likely a problem with your bucket.
2. Can the `api_z1` vm access the bucket at all? Again, consider installing s3cmd on that machine and attempting to list the objects in the bucket. If not, then your networking configuration is such that the deployed VMs can't communicate with s3. You'd have to take a look at your [AWS Security Groups](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html), or potentially even the [Route Tables](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Route_Tables.html) and make sure you allow network traffic from the VM to the s3 bucket.
3. How long does it take to PUT a new object in the bucket? If it's longer than 5 seconds, it exceeds your timeout.

Hope that helps!

**Comment by Senthilannaswamy** [comment]
HI Dsabeti,

Yes, looks like network issue. 

I was able to access/put on S3 using the following command, from the VM where I do `bosh deploy`.

> s3cmd put TODO s3://sys-offshore-magellancloud-com-cc-buildpacks

Whereas, `api_z1 vm` and `api_worker_z1`, is unable to `wget`, getting below error (though security group has all ports open and public ip is assigned)

> Connecting to github.com (github.com)|192.30.253.112|:443... failed: Connection timed out.

Please suggest, whether any incorrect configuration.

Thanks
Senthil

**Comment by dsabeti** [comment]
@Senthilannaswamy. Like I said, you'll have to look at your AWS Security groups to make sure your network is configured such that VMs in your bosh deployment can communicate with s3.

**Comment by Senthilannaswamy** [comment]
Hi Dsabeti,

Yes, there were some black hole. Post fixing those, all VMs are created without any issues.

Thanks
Senthil.

**Comment by dsabeti** [comment]
Great! Glad you found the problem.
