### ISSUE TITLE
incompatible character encodings: UTF-8 and US-ASCII  

### ISSUE THREAD

**Issue by ligb** [cloudfoundry/cf-release#1234]
cf:269
openstack:ocata
bosh-openstack-cpi:bosh-openstack-cpi-release-33.tgz
bosh-262.3-ubuntu-trusty-3421.9-20170706-183731-831697577-20170706183736.tgz
stemcell: bosh-stemcell-3445.2-openstack-kvm-ubuntu-trusty-go_agent.tgz
director-stemcell:bosh-stemcell-3421.9-openstack-kvm-ubuntu-trusty-go_agent.tgz

when' bosh deploy', I have the issue:
```
  Started creating missing vms > stats_z1/fd78fb64-f871-4cf3-b0cc-178b096aaca7 (0)
  Started creating missing vms > consul_z1/88736fdb-109e-4e2f-b452-9abfc90ac0fa (0)
  Started creating missing vms > doppler_z1/7dfa869a-4798-45ad-ad01-e68d6bcc0702 (0)
  Started creating missing vms > postgres_z1/4938fccd-ec31-49bb-9180-3f15487fcbca (0)
  Started creating missing vms > clock_z1/953d3a85-03b3-42e4-adfa-81da22b94605 (0)
  Started creating missing vms > ha_proxy_z1/14ee5f4c-d1dd-4e9d-b0ff-114278ad0d34 (0)
  Started creating missing vms > router_z1/8ac35bdc-84a7-4937-80bf-f1d06bee3db3 (0)
  Started creating missing vms > blobstore_z1/e4da6b1b-5222-43d2-8869-3d1eb9a466fc (0)
  Started creating missing vms > loggregator_trafficcontroller_z1/956f579d-7d5f-4fa3-96b4-8754e68ec711 (0)
  Started creating missing vms > api_z1/dc6472f6-2fef-4985-b905-cd77be32aadf (0)
   Failed creating missing vms > blobstore_z1/e4da6b1b-5222-43d2-8869-3d1eb9a466fc (0): incompatible character encodings: UTF-8 and US-ASCII (00:00:11)
   Failed creating missing vms > router_z1/8ac35bdc-84a7-4937-80bf-f1d06bee3db3 (0): incompatible character encodings: UTF-8 and US-ASCII (00:00:11)
   Failed creating missing vms > ha_proxy_z1/14ee5f4c-d1dd-4e9d-b0ff-114278ad0d34 (0): incompatible character encodings: UTF-8 and US-ASCII (00:00:11)
   Failed creating missing vms > loggregator_trafficcontroller_z1/956f579d-7d5f-4fa3-96b4-8754e68ec711 (0): incompatible character encodings: UTF-8 and US-ASCII (00:00:11)
     Done creating missing vms > api_z1/dc6472f6-2fef-4985-b905-cd77be32aadf (0) (00:01:36)
   Failed creating missing vms > clock_z1/953d3a85-03b3-42e4-adfa-81da22b94605 (0): Timed out pinging to 8bb4589c-141b-46e3-8541-9fd65b1fc683 after 600 seconds (00:10:33)
   Failed creating missing vms > consul_z1/88736fdb-109e-4e2f-b452-9abfc90ac0fa (0): Timed out pinging to 1081521b-b07a-4642-850c-df5bc853cedc after 600 seconds (00:10:34)
   Failed creating missing vms > stats_z1/fd78fb64-f871-4cf3-b0cc-178b096aaca7 (0): Timed out pinging to 8ff559d1-a210-4bcd-b21d-e564b5e4b505 after 600 seconds (00:10:35)
   Failed creating missing vms > doppler_z1/7dfa869a-4798-45ad-ad01-e68d6bcc0702 (0): Timed out pinging to 674a681d-5437-468e-b02d-778e9ccfda8f after 600 seconds (00:10:35)
   Failed creating missing vms > postgres_z1/4938fccd-ec31-49bb-9180-3f15487fcbca (0): Timed out pinging to 45ccae1a-8224-42f1-aefe-cd936544395b after 600 seconds (00:10:35)
   Failed creating missing vms (00:10:35)
Error 100: incompatible character encodings: UTF-8 and US-ASCII
```
1  I  have two 32G Mem compute nodes . From error, I think this is one factor.  so, what's the reason for 'incompatible character encodings: UTF-8 and US-ASCII '
2.  it's a problem about rudy?,  I try set LANG=en_US.UTF-8 , LC_ALL=en_US.UTF-8 , but doesn't work.

task debug:
```
D, [2017-08-17 16:30:28 #26385] [create_missing_vm(postgres_z1/4938fccd-ec31-49bb-9180-3f15487fcbca (0)/10)] DEBUG -- DirectorJobRunner: (0.003983s) COMMIT
E, [2017-08-17 16:30:28 #26385] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Timed out pinging to 45ccae1a-8224-42f1-aefe-cd936544395b after 600 seconds - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:214:in `rescue in wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:220:in `wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:70:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:34:in `block (5 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:31:in `block (4 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:30:in `block (3 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-08-17 16:30:28 #26385] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.001303s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.001021s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON ("deployments_stemcells"."stemcell_id" = "stemcells"."id") WHERE ("deployments_stemcells"."deployment_id" = 1)
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000205s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000584s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000350s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.013578s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:cf') AND ("uid" = '72c8af58-4317-47ac-b9b0-8f6c160324fe'))
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf uid: 72c8af58-4317-47ac-b9b0-8f6c160324fe
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000277s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000117s) BEGIN
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000470s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2017-08-17 16:30:28.690672+0000', 'admin', 'release', 'lock', 'lock:deployment:cf', NULL, '31', 'cf', NULL, '{}') RETURNING *
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.014141s) COMMIT
I, [2017-08-17 16:30:28 #26385] [task:31]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"fc1e3458-414d-4e52-929a-dda90304dde5","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf' against Director '361536b9-9d26-4e6e-8bc2-da8a0781989a': #<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and US-ASCII>","created_at":1502987428,"deployment":"cf"}
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000144s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000056s) BEGIN
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000223s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (722, '2017-08-17 16:30:28.707681+0000', 'admin', 'update', 'deployment', 'cf', 'incompatible character encodings: UTF-8 and US-ASCII', '31', 'cf', NULL, '{"before":{"releases":["cf/269+dev.5"],"stemcells":["bosh-openstack-kvm-ubuntu-trusty-go_agent/3445.2"]},"after":{"releases":["cf/269+dev.5"],"stemcells":["bosh-openstack-kvm-ubuntu-trusty-go_agent/3445.2"]}}') RETURNING *
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.011523s) COMMIT
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000124s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000188s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000442s) SELECT * FROM "deployments" WHERE ("name" = 'cf') LIMIT 1
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000188s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000547s) SELECT * FROM "variable_sets" WHERE ("variable_sets"."deployment_id" = 1) ORDER BY "created_at" DESC LIMIT 1
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000159s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000087s) BEGIN
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000278s) UPDATE "variable_sets" SET "writable" = false WHERE ("id" = 11)
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.004055s) COMMIT
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000176s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000119s) BEGIN
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000390s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1502987428,"error":{"code":100,"message":"incompatible character encodings: UTF-8 and US-ASCII"}}
') WHERE ("id" = 31)
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.002819s) COMMIT
E, [2017-08-17 16:30:28 #26385] [task:31] ERROR -- DirectorJobRunner: incompatible character encodings: UTF-8 and US-ASCII
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:86:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:52:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:187:in `create'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:57:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:34:in `block (5 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:31:in `block (4 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/vm_creator.rb:30:in `block (3 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000106s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000244s) SELECT * FROM "tasks" WHERE ("id" = 31) LIMIT 1
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000157s) SELECT NULL
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000072s) BEGIN
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.000508s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-08-17 16:30:28.738407+0000', "description" = 'create deployment', "result" = 'incompatible character encodings: UTF-8 and US-ASCII', "output" = '/var/vcap/store/director/tasks/31', "checkpoint_time" = '2017-08-17 16:30:17.763103+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf', "started_at" = '2017-08-17 16:19:47.625733+0000', "event_output" = '{"time":1502986787,"type":"deprecation","message":"Ignoring cloud config. Manifest contains ''networks'' section."}
{"time":1502986787,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"started","progress":0}
{"time":1502986789,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"finished","progress":100}
{"time":1502986792,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"started","progress":0}
{"time":1502986793,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"finished","progress":100}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"stats_z1/fd78fb64-f871-4cf3-b0cc-178b096aaca7 (0)","index":2,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"consul_z1/88736fdb-109e-4e2f-b452-9abfc90ac0fa (0)","index":1,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"doppler_z1/7dfa869a-4798-45ad-ad01-e68d6bcc0702 (0)","index":7,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"postgres_z1/4938fccd-ec31-49bb-9180-3f15487fcbca (0)","index":4,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"clock_z1/953d3a85-03b3-42e4-adfa-81da22b94605 (0)","index":6,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"ha_proxy_z1/14ee5f4c-d1dd-4e9d-b0ff-114278ad0d34 (0)","index":10,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"router_z1/8ac35bdc-84a7-4937-80bf-f1d06bee3db3 (0)","index":9,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"blobstore_z1/e4da6b1b-5222-43d2-8869-3d1eb9a466fc (0)","index":3,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"loggregator_trafficcontroller_z1/956f579d-7d5f-4fa3-96b4-8754e68ec711 (0)","index":8,"state":"started","progress":0}
{"time":1502986793,"stage":"Creating missing vms","tags":[],"total":10,"task":"api_z1/dc6472f6-2fef-4985-b905-cd77be32aadf (0)","index":5,"state":"started","progress":0}
{"time":1502986804,"stage":"Creating missing vms","tags":[],"total":10,"task":"blobstore_z1/e4da6b1b-5222-43d2-8869-3d1eb9a466fc (0)","index":3,"state":"failed","progress":100,"data":{"error":"incompatible character encodings: UTF-8 and US-ASCII"}}
{"time":1502986804,"stage":"Creating missing vms","tags":[],"total":10,"task":"router_z1/8ac35bdc-84a7-4937-80bf-f1d06bee3db3 (0)","index":9,"state":"failed","progress":100,"data":{"error":"incompatible character encodings: UTF-8 and US-ASCII"}}
{"time":1502986804,"stage":"Creating missing vms","tags":[],"total":10,"task":"ha_proxy_z1/14ee5f4c-d1dd-4e9d-b0ff-114278ad0d34 (0)","index":10,"state":"failed","progress":100,"data":{"error":"incompatible character encodings: UTF-8 and US-ASCII"}}
{"time":1502986804,"stage":"Creating missing vms","tags":[],"total":10,"task":"loggregator_trafficcontroller_z1/956f579d-7d5f-4fa3-96b4-8754e68ec711 (0)","index":8,"state":"failed","progress":100,"data":{"error":"incompatible character encodings: UTF-8 and US-ASCII"}}
{"time":1502986889,"stage":"Creating missing vms","tags":[],"total":10,"task":"api_z1/dc6472f6-2fef-4985-b905-cd77be32aadf (0)","index":5,"state":"finished","progress":100}
{"time":1502987426,"stage":"Creating missing vms","tags":[],"total":10,"task":"clock_z1/953d3a85-03b3-42e4-adfa-81da22b94605 (0)","index":6,"state":"failed","progress":100,"data":{"error":"Timed out pinging to 8bb4589c-141b-46e3-8541-9fd65b1fc683 after 600 seconds"}}
{"time":1502987427,"stage":"Creating missing vms","tags":[],"total":10,"task":"consul_z1/88736fdb-109e-4e2f-b452-9abfc90ac0fa (0)","index":1,"state":"failed","progress":100,"data":{"error":"Timed out pinging to 1081521b-b07a-4642-850c-df5bc853cedc after 600 seconds"}}
{"time":1502987428,"stage":"Creating missing vms","tags":[],"total":10,"task":"stats_z1/fd78fb64-f871-4cf3-b0cc-178b096aaca7 (0)","index":2,"state":"failed","progress":100,"data":{"error":"Timed out pinging to 8ff559d1-a210-4bcd-b21d-e564b5e4b505 after 600 seconds"}}
{"time":1502987428,"stage":"Creating missing vms","tags":[],"total":10,"task":"doppler_z1/7dfa869a-4798-45ad-ad01-e68d6bcc0702 (0)","index":7,"state":"failed","progress":100,"data":{"error":"Timed out pinging to 674a681d-5437-468e-b02d-778e9ccfda8f after 600 seconds"}}
{"time":1502987428,"stage":"Creating missing vms","tags":[],"total":10,"task":"postgres_z1/4938fccd-ec31-49bb-9180-3f15487fcbca (0)","index":4,"state":"failed","progress":100,"data":{"error":"Timed out pinging to 45ccae1a-8224-42f1-aefe-cd936544395b after 600 seconds"}}
{"time":1502987428,"error":{"code":100,"message":"incompatible character encodings: UTF-8 and US-ASCII"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 31)
D, [2017-08-17 16:30:28 #26385] [task:31] DEBUG -- DirectorJobRunner: (0.002639s) COMMIT
I, [2017-08-17 16:30:28 #26385] []  INFO -- DirectorJobRunner: Task took 10 minutes 41.12750884100001 seconds to process.
```

**Comment by dsabeti** [comment]
Hi @ligb, this looks to be an issue with BOSH (rather than cf-release), so let's get some help from the team that works on the OpenStack CPI.

**Comment by dsabeti** [comment]
Ok, @voelzmo and his team will try to help out after the weekend.

**Comment by voelzmo** [comment]
Corresponding story in our backlog: https://www.pivotaltracker.com/story/show/150369990

**Comment by friegger** [comment]
Hi @libg, we have analyzed the issue. From what we've learned it looks like that the affected `create_vm` calls fail and the errors contain non-ascii characters. The BOSH director and the workers currently run with external default encoding `US_ASCII` which causes STDOUT and STDERR of the shell out to the CPI being force encoded to `US_ASCII`. This leads, under certain circumstances, to the `incompatible character encodings: UTF-8 and US-ASCII` error. For more details, see https://www.pivotaltracker.com/n/projects/1456570/stories/150369990.

To confirm out assumption, are there any non-ascii characters in-use in your OpenStack setup, project name, etc that you are aware of?

Nevertheless, the director and workers should run with `Encoding.default_external = Encoding::UTF_8` and we will work on a fix.

**Comment by ligb** [comment]
@friegger   actually, I checked my confiuration when I met this issue, all settings about openstack or bosh that need to be modified  are in English,  project name, az ,etc.  except my openstack dashboard , which is  zh-cn. this is the problem?

**Comment by friegger** [comment]
Yes, our assumption is, that the failing jobs failed due to another reason and the encoding errors just "hide" those other errors and only occurs in case of an error, so we don't see this problem in `api_z1`.

It's hard to tell, where the unicode character is included. Unfortunately, the error occurs when BOSH tries to log the detailed CPI response, so we don't see it in the logs. The part of the task debug log, where `api_z1` is created successfully might be interesting. You would find the logs with `excon.request` or `excon.response`. Make sure to redact any sensitive information.

If it is a dev environment, can you `sudo` on the BOSH VM or are you familiar with creating a dev release of BOSH? Than you could either apply the changes of the PR on the VM and restart the processes or redeploy BOSH with a dev release containing those changes. Otherwise you need to wait until a the next BOSH release which hopefully contains the PR.

**Comment by dsabeti** [comment]
Hi everyone. It's been more than a month without activity on this issue. Should we close this out, or is there more to do?

**Comment by friegger** [comment]
@dsabeti The fix has been provided and should be part of BOSH 264 when it is released. I would suggest to close the issue and @ligb can reopen it (possibly on BOSH) in case the problem persists on their infrastructure.

**Comment by dsabeti** [comment]
Great, thanks!
