### ISSUE TITLE
Failed to perform blobstore operation after three retries

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cf-release#1258]
CF v275
Openstack
Swift as blobstore

We got the following error ~6 times today (during a simple cf-push test)

```
cloud_controller_ng/cloud_controller_ng.log.6.gz:37629:{"timestamp":1508758108.2582684,"message":"Request failed: 500: {\"description\"=>\"Failed to perform blobstore operation after three retries.\", \"error_code\"=>\"CF-BlobstoreError\", \"code\"=>150007, \"test_mode_info\"=>{\"description\"=>\"Failed to perform blobstore operation after three retries.\", \"error_code\"=>\"CF-BlobstoreError\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/12e78d7c1a4c5cd73d98f45b2825f8df46280447/cloud_controller_ng/app/jobs/logging_context_job.rb:20:in `rescue in perform'\", \"/var/vcap/data/packages/cloud_controller_ng/12e78d7c1a4c5cd73d98f45b2825f8df46280447/cloud_controller_ng/app/jobs/logging_context_job.rb:15:in `perform'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:175:in `block (4 levels) in start'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:174:in `block (3 levels) in start'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:173:in `block (2 levels) in start'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `loop'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `block in start'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block in add'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:171:in `start'\", \"/var/vcap/data/packages/cloud_controller_ng/12e78d7c1a4c5cd73d98f45b2825f8df46280447/cloud_controller_ng/lib/tasks/jobs.rake:51:in `start_working'\", \"/var/vcap/data/packages/cloud_controller_ng/12e78d7c1a4c5cd73d98f45b2825f8df46280447/cloud_controller_ng/lib/tasks/jobs.rake:16:in `block (2 levels) in <top (required)>'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<top (required)>'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'\", \"/var/vcap/packages/ruby-2.3/bin/bundle:22:in `load'\", \"/var/vcap/packages/ruby-2.3/bin/bundle:22:in `<main>'\"]}}","log_level":"error","source":"cc.background","data":{"request_guid":"c43f1928-7011-4d2f-b837-1f245719f9c3","job_guid":"13d31307-bd3f-4077-b147-64e2acaa4bd7"},"thread_id":47346716545300,"fiber_id":47346756621700,"process_id":5524,"file":"/var/vcap/data/packages/cloud_controller_ng/12e78d7c1a4c5cd73d98f45b2825f8df46280447/cloud_controller_ng/app/jobs/logging_context_job.rb","lineno":43,"method":"block in log_error"}
```

do you think this is a swift issue or could it be a CF one?

How can I further debug this issue?

**Comment by dsabeti** [comment]
Hey @paolostivanin. Let's get some help from the CAPI team. @Gerg @zrob, can someone from CAPI take a look at this?

**Comment by Gerg** [comment]
Hey @paolostivanin,

This is a generic error that occurs whenever cloud controller and the blobstore are unable to communicate. You will have to look at the cloud controller logs for a more detailed error message to help debug the root cause.

Thanks,
Greg

**Comment by paolostivanin** [comment]
Ok, I think I've found something:

```
vcap.cloud_controller_ng [job=api_z1 index=1]  {"timestamp":1508757537.4785168,"message":"blobstore error: connect_write timeout reached","log_level":"error","source":"cc.resource_pool","data":{"request_guid":"db82e412-0851-42a3-5e43-1d9b2d9a06fd::95ac74ab-75c3-4339-93df-efeb4f0c4a07"},"thread_id":47293160814880,"fiber_id":70344680542460,"process_id":5540,"file":"/var/vcap/data/packages/cloud_controller_ng/12e78d7c1a4c5cd73d98f45b2825f8df46280447/cloud_controller_ng/lib/cloud_controller/resource_pool.rb","lineno":106,"method":"rescue in resource_known?"}
```

**Comment by Gerg** [comment]
It looks like cloud controller is timing out trying to talk to the blobstore. See if you can connect to the blobstore normally from the CC's vm. Also, check any timeouts you have configured.

**Comment by paolostivanin** [comment]
ok, thanks :)
