### ISSUE TITLE
Failed Jobs: uaa on vSphere

### ISSUE THREAD

**Issue by sirjune** [cloudfoundry/cf-release#1261]
Hi, 
I am getting this error when trying to apply changes to OpsManager.  I thought this is similar to #1164 but i can't login to the VM to get the logs.  I'd appreciate if someone can give me directions/hints to troubleshoot this.

Thanks!
sirjune

Task 212 | 19:46:51 | Preparing deployment: Preparing deployment (00:00:10)
Task 212 | 19:47:21 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 212 | 19:47:23 | Updating instance uaa: uaa/a06285e7-378a-4ed9-a5d8-1753043bf321 (0) (canary) (00:01:44)
                    L Error: Action Failed get_task: Task f8971a4f-9c7a-48eb-55eb-f17c3da08cc8 result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.
Task 212 | 19:49:07 | Error: Action Failed get_task: Task f8971a4f-9c7a-48eb-55eb-f17c3da08cc8 result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.

**Comment by dsabeti** [comment]
@sirjune, you should still be able to pull down the logs by running `bosh logs uaa 0`.

cc @fhanik @jhamon, to help out once you pull down the logs.

**Comment by sirjune** [comment]
ok. i was able to ssh to uaa VM and pull the logs..  let me start with "ERROR" keyword. I am really not sure where to look this in the Elastic Runtime settings.... 

[2017-11-13 22:01:07.333] uaa - 20806 [localhost-startStop-1] .... ERROR --- YamlConfigurationValidator: Failed to load YAML validation bean. Your YAML file may be invalid.
Cannot create property=scim for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration@2a8d43b8
 in 'string', line 1, column 1:
    scim:
    ^
Cannot create property=user for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Scim@55d37327
 in 'string', line 2, column 3:
      groups: {zones.read: Read identi ...
      ^
Unable to find property 'user' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Scim
 in 'string', line 19, column 9:
      user: {override: true}
            ^

 in 'string', line 2, column 3:
      groups: {zones.read: Read identi ...
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)

**Comment by sirjune** [comment]
Secondly,  i found this keyword  "adcslab-uaa"  that i supplied in the JWT Issuer URI field.  

[2017-11-13 22:01:08.593] uaa - 20806 [localhost-startStop-1] ....  WARN --- XmlWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.filterChains': Cannot resolve reference to bean 'secFilterLoginServerAuthenticate' while setting bean property 'sourceList' with key [16]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'secFilterLoginServerAuthenticate': Cannot resolve reference to bean 'oauthResourceAuthenticationFilter' while setting constructor argument with key [3]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oauthResourceAuthenticationFilter': Cannot create inner bean '(inner bean)#63b06c90' of type [org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager] while setting bean property 'authenticationManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#63b06c90': Cannot resolve reference to bean 'tokenServices' while setting bean property 'tokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenServices' defined in ServletContext resource [/WEB-INF/spring/oauth-endpoints.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'issuer' threw exception; nested exception is java.net.URISyntaxException: no protocol: adcslab-uaa: adcslab-uaa
[2017-11-13 22:01:08.593] uaa - 20806 [localhost-startStop-1] ....  INFO --- MBeanExporter: Unregistering JMX-exposed beans on shutdown
[2017-11-13 22:01:08.594] uaa - 20806 [localhost-startStop-1] ....  INFO --- MBeanExporter: Unregistering JMX-exposed beans on shutdown
[2017-11-13 22:01:08.610] uaa - 20806 [localhost-startStop-1] .... ERROR --- DispatcherServlet: Context initialization failed

**Comment by fhanik** [comment]
>java.net.URISyntaxException: no protocol: adcslab-uaa: adcslab-uaa

looks like you are trying to set the configuration option `issuer` with an invalid URL. Reopen if you need more help
