### ISSUE TITLE
Special characters in passwords cause deployment to fail

### ISSUE THREAD

**Issue by matjohn2** [cloudfoundry/cf-release#493]
Hi All,

#### Issue 
Entering an '@' (and possibly other chars) within a CF deployment manifest causes the deployment to fail.

In our scenario, we saw the UAA job fail to run, investigation showed the password was being used in a URI string made up of http://<username>:<password>@<host>:<port>. The extra @'s were causing a malformed URI.

### Reproducing
The following snippet of deployment manifest should do it.

        uaa:
            admin:
                client_secret: L@zyp@ssword@

#### UAA/0 Log

        /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize': the scheme nats does not accept registry part: nats:L@zyp@ssword@0.nats.internalPAAS.cf-deployment-name.microbosh:4222 (or bad hostname?) (URI::InvalidURIError)
                from /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/common.rb:218:in `new'
                from /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/common.rb:218:in `parse'
                from /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/nats-0.5.0.beta.12/lib/nats/client.rb:133:in `connect'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/cf-message-bus-0.2.0/lib/cf_message_bus/message_bus_factory.rb:6:in `message_bus'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/cf-message-bus-0.2.0/lib/cf_message_bus/message_bus.rb:12:in `initialize'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/cache/cf-registrar-49850ee87665/lib/cf/registrar.rb:93:in `new'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/cache/cf-registrar-49850ee87665/lib/cf/registrar.rb:93:in `message_bus'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/cache/cf-registrar-49850ee87665/lib/cf/registrar.rb:66:in `register_with_router'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/cache/cf-registrar-49850ee87665/bin/cf-registrar:44:in `block in <top (required)>'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/cache/cf-registrar-49850ee87665/bin/cf-registrar:32:in `<top (required)>'
                from /var/vcap/packages/uaa/vcap-common/bin/cf-registrar:16:in `load'
                from /var/vcap/packages/uaa/vcap-common/bin/cf-registrar:16:in `<main>'
        /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize': the scheme nats does not accept registry part: nats:L@z@ruspaaspass@0.nats.internalPAAS.cf-cdfw0-lazarus-production.microbosh:4222 (or bad hostname?) (URI::InvalidURIError)
                from /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/common.rb:218:in `new'
                from /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/common.rb:218:in `parse'
                from /var/vcap/packages/ruby/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/nats-0.5.0.beta.12/lib/nats/client.rb:133:in `connect'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/cf-message-bus-0.2.0/lib/cf_message_bus/message_bus_factory.rb:6:in `message_bus'
                from /var/vcap/data/packages/uaa/49.1/vcap-common/vendor/bundle/ruby/1.9.1/gems/cf-message-bus-0.2.0/lib/cf_message_bus/message_bus.rb:12:in `initialize'
        cf-registrar.stderr.log

**Comment by Amit-PivotalLabs** [comment]
Closing due to inactivity.  We've created a [story](https://www.pivotaltracker.com/story/show/98993492) for later prioritization that will improve how URLs are constructed from manifest properties, across the board.

**Comment by Amit-PivotalLabs** [comment]
For the record, we investigated this issue, but the number of components and libraries (some third-party) that would require fixes and pull requests was too high, and supporting unusual characters is in these sorts of passwords is not a high priority.  It's also likely that the changes required to fix this would cause downtime during a rolling deploy, until the new behaviour has rolled through both clients and servers.

**Comment by aemengo** [comment]
@mbildner says:

Hi @Amit-PivotalLabs - after investigating the issue further we think it still poses a real security risk and is worth addressing. We have no opinion about what kind of passwords you decide to support or how the logging gets suppressed (or sanitized or cleared...) but we think it's a high enough risk that it is worth taking action to prevent the logging of this password in the clear to syslog.

There's a tracker ticker [here](https://www.pivotaltracker.com/story/show/139197157) that we have assigned to the relint team.

cc @dsabeti 

Thanks,
PCF Security Triage

**Comment by dieucao** [comment]
@aemengo That item seems related and has the same cause but I don't think it makes sense to couple the issues together.
