### ISSUE TITLE
generate-bosh-lite-dev-manifest failing

### ISSUE THREAD

**Issue by bhudlemeyer** [cloudfoundry/cf-release#896]
Right before I submitted this I found my issue. I still wanted to submit though as I didn't find this here and just happened to stumble across it in an unrelated thread.

 had to install ruby bundle
gem install bundle

Also sorry this is probably a very newb mistake but just starting and did not see this listed anywhere.

```
+ git clean -ffd
+ set +x
CF Release has been updated
+ ./scripts/generate-bosh-lite-dev-manifest
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Can only target Bosh Lite Director. Please use 'bosh target' before running this script.

cf-release]$ ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

pwd
/home/bh/cf-release

[@ cf-release]$ bosh -v
BOSH 1.3184.1.0

[@cf-release]$ alias bosh
bash: alias: bosh: not found

cf-release]$ git log -n1
commit b1c839f8682a61542e2ab4e65865b3426ae65455
Author: Amit Kumar Gupta <agupta@pivotal.io>
Date:   Mon Jan 25 13:50:23 2016 -0800

    Revert "Merge upstream changes"
    
    This reverts commit 94f597f5fc2b843a392c8b475e8946c35ec15622, reversing
    changes made to 3c73e6d21d24061dcd56ba141e2fca5f50600eb7.

cf-release]$ ls -altr bosh-lite/
total 4
drwxrwxr-x  2 bh bh   92 Jan 26 14:31 stubs
drwxrwxr-x  3 bh bh   18 Jan 26 14:31 .
drwxrwxr-x 21 bh bh 4096 Jan 27 08:55 ..

cf-release]$ git status
# On branch master
nothing to commit, working directory clean

cf-release]$ bosh target
Current target is https://192.168.50.4:25555 (Bosh Lite Director)

[@ cf-release]$ bosh status
Config
             /home/bh/.bosh_config

Director
  Name       Bosh Lite Director
  URL        https://192.168.50.4:25555
  Version    1.3173.0 (00000000)
  User       admin
  UUID       3e42d17f-072b-4577-8446-d1e15bb59f49
  CPI        warden_cpi
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

Deployment
  not set

cf-release]$ ls /usr/local/bin/ | grep -i spiff
spiff (version 1.0.7)

Running 
cf-release]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

```

**Comment by robdimsdale** [comment]
@bhudlemeyer that sounds like you fixed it, but I also created [a tracker story](https://www.pivotaltracker.com/story/show/112554035) to fail fast with a better error message - thanks for bringing this to our attention.

I'll close this issue now.
