### ISSUE TITLE
Time out in downloading python-buildpack blob while provisioning cloud foundry on bosh lite 

### ISSUE THREAD

**Issue by rphukan** [cloudfoundry/cf-release#983]
I have been trying to provisioning cloud foundry on bosh lite. For that I am following the steps below
1. start bosh vm
2. login to bosh as admin
3. run the cloud foundry provision scripts
./bin/add-route
./bin/provision_cf
but every time it  breaks with below trace while running the provision script

```
Creating cf-release release
Syncing blobs...
python-buildpack/python_buildpack-cached-... downloading 254.1M
/var/lib/gems/2.1.0/gems/blobstore_client-1.3215.3.0/lib/blobstore_client/base.rb:63:in `rescue in get': Failed to fetch object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired> /usr/lib/ruby/2.1.0/openssl/buffering.rb:129:in `sysread' (Bosh::Blobstore::BlobstoreError)
/usr/lib/ruby/2.1.0/openssl/buffering.rb:129:in `readpartial'
/var/lib/gems/2.1.0/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:86:in `readpartial'
/var/lib/gems/2.1.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:870:in `block in read_body_length'
/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `call'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
```
Initially I thought it to be a network issue and tried several times but  without success. 
I actually had it up and running before. But the cloud foundry vms started failing and I cloud not revive them and hence doing the complete provisioning again. Any kind of help and suggestions would be very much appreciated.

**Comment by APShirley** [comment]
Hi @rphukan, 
Could you start by telling us what version/branch of CF you are deploying off of?
We just attempted this with master on a clean clone of cf-release & bosh-lite and it worked fine.
Thanks,
Al

**Comment by rphukan** [comment]
Hi
Thanks for looking into it. I am also on master branch of both cf-release and bosh-lite. I tried it again today with the latest code but still getting the same error. Here are some other details.
1. BOSH 1.3215.3.0
2. with latest vagrant box 'cloudfoundry/bosh-lite'
3. Stemcell 
Name:    bosh-warden-boshlite-ubuntu-trusty-go_agent
Version: 3147
Thanks
Ranjan

**Comment by APShirley** [comment]
Hi @rphukan 

That is strange. Can you let us know the following:

1) Is the error consistently failing to download `python-buildpack/python_buildpack-cached-` or is it a different blob every time?

2) Can you try `wget http://cf-release-blobs.s3.amazonaws.com/cd1d3598-ff44-4752-9826-0fb80223ff95` to see if you can successfully download the buildpack manually? If this works, you can fetch the sha from `config/blobs.yml`, save the downloaded buildpack as `cf-release/.blobs/<sha of python buildpack>`, and then try running `bosh create release` in your `cf-release` directory. This should skip downloading the python buildpack (because it's already in your `.blobs` directory).

If creating the release keeps failing to download other buildpacks, then you may have a networking issue.

Thanks,

Alvaro & @dsabeti

**Comment by APShirley** [comment]
Hi @rphukan,

Since there has been no activity on this issue in 2 weeks we are going to close this issue. If you need further help feel free to open a new issue.

Thanks,

Alvaro

**Comment by rphukan** [comment]
Finally I have completed the set up. Not sure what was the exact problem, may be a network issue. I just kept on trying after every failure and one fine day got this up and running after several attempts and consuming nearly 12 GBs of data.
