### ISSUE TITLE
cf-push returns "Error restarting application: StagingError"

### ISSUE THREAD

**Issue by srinat999** [cloudfoundry/cf-release#990]
So I have been trying to set up CF on Openstack and have been facing many issues as mentioned #975. Just thought of creating a new issue as I have come a long way from when I started that issue.

After a lot of struggle I finally managed to get CF up and running on Openstack and I am able to login. However, I cannot push any apps:

```
$ cf push test-app
Updating app test-app in org openstackindia / space development as admin...
OK

Uploading test-app...
Uploading app files from: /home/ubuntu/my-bosh/test-app
Uploading 203.7K, 116 files
Done uploading
OK

Stopping app test-app in org openstackindia / space development as admin...
OK

Warning: error tailing logs
Error dialing traffic controller server: Forbidden port.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.sys-cfisbtest.it-platforms.net:4443).
Starting app test-app in org openstackindia / space development as admin...

FAILED
Error restarting application: StagingError

TIP: use 'cf logs test-app --recent' for more information
```

I looked into the relevant logs in dea_next under the runner VM and here is what I could find

```
{"timestamp":1466611294.1785636,"message":"em-upload.polling.handle_error","log_level":"warn","source":"Staging","data":{"app_guid":"4017b1d6-9ee3-4faa-a657-e2de5ba605c4","task_id":"6fa069421fba40d6bbaf7a0308dcf9d2"},"thread_id":46941950179720,"fiber_id":46941963479460,"process_id":17238,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":90,"method":"block in poll"}
{"timestamp":1466611294.1789405,"message":"em-upload.error","log_level":"warn","source":"Staging","data":{"app_guid":"4017b1d6-9ee3-4faa-a657-e2de5ba605c4","task_id":"6fa069421fba40d6bbaf7a0308dcf9d2","destination":"http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/4017b1d6-9ee3-4faa-a657-e2de5ba605c4/upload","connection_count":9,"message":"Error uploading: (Polling failed - status 0; error: unable to resolve server address)","http_error":"unable to resolve server address","http_status":0,"http_response":""},"thread_id":46941950179720,"fiber_id":46941963479460,"process_id":17238,"file":"/var/vcap/packages/dea_next/lib/dea/utils/upload.rb","lineno":58,"method":"handle_error"}
{"timestamp":1466611294.179245,"message":"staging.task.droplet-upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"4017b1d6-9ee3-4faa-a657-e2de5ba605c4","task_id":"6fa069421fba40d6bbaf7a0308dcf9d2","duration":null,"destination":"http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/4017b1d6-9ee3-4faa-a657-e2de5ba605c4/upload","error":"Error uploading: (Polling failed - status 0; error: unable to resolve server address)","backtrace":null},"thread_id":46941950179720,"fiber_id":46941963479460,"process_id":17238,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":347,"method":"block (2 levels) in promise_app_upload"}
{"timestamp":1466611294.1795235,"message":"staging.task.upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"4017b1d6-9ee3-4faa-a657-e2de5ba605c4","task_id":"6fa069421fba40d6bbaf7a0308dcf9d2","error":"Error uploading: (Polling failed - status 0; error: unable to resolve server address)","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:606:in `resolve_staging_upload'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:65:in `block in start'","/var/vcap/packages/dea_next/lib/dea/promise.rb:20:in `block in resolve'"]},"thread_id":46941950179720,"fiber_id":46941962913140,"process_id":17238,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":67,"method":"rescue in block in start"}
```

As you can see its not able to resolve the CC while trying to upload the droplet. This is really confusing. Because I am able to curl into that endpoint ```http://cloud-controller-ng.service.cf.internal:9022/staging/droplets/4017b1d6-9ee3-4faa-a657-e2de5ba605c4/upload```.

Here is the nslookup on that endpoint:

```
bosh_hcp8s31az@862a0c35-8aa7-401e-bca7-5a0862123be2:/var/vcap/sys/log/dea_next$ nslookup cloud-controller-ng.service.cf.internal
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   cloud-controller-ng.service.cf.internal
Address: 30.0.0.104
```

Here is my current yaml file: 
[cf-deployment_cropped.txt](https://github.com/cloudfoundry/cf-release/files/328283/cf-deployment_cropped.txt)

Any help is deeply appreciated. 

PS: I am also under a corporate proxy, and the proxy is not set on the individual VMs. Which means they do not have connectivity to the internet.

**Comment by DennisDenuto** [comment]
Hey @srinat999 
The fact you were able to perform a nslookup from the dea to the cc is rather strange.

Did you try staging 'test-app' after you were able to perform the nslookup from the dea?

Also we suspect that maybe the dns resolution (via consul) to cc is flakey. Can you please run the following command and provide us the output from `/tmp/nslookup.log`:

```
for x in `seq 1 120`; do nslookup cloud-controller-ng.service.cf.internal; sleep 1; done > /tmp/nslookup.log
``` 

Thanks
Dennis && @dsabeti 
CF Release Integration Team

**Comment by srinat999** [comment]
Hey, Thanks for the reply. Sorry for not responding earlier, as I am working on this only 2 days a week.

I managed to get this working. The problem was my CF public API (api.sys-cfisbtest.it-platforms.net) endpoint was not reacheble from the dea VM as I am under a proxy. Added a direct to mapping to that and it worked. 

I also managed to push this app (https://github.com/cloudfoundry-samples/test-app) and I think its working. I am able to access the end point for that particular app. However I am neither not able to push a Java app (https://github.com/cloudfoundry-samples/spring-music) nor a ruby app. The cf apps command also doesn't look ideal:

```
Getting apps in org openstackindia / space development as admin...
OK

name           requested state   instances   memory   disk   urls
spring-music   started           0/1         512M     1G     spring-music-absolvent-peytral.app-cfisbtest.it-platforms.net
test-app       started           ?/1         1G       1G     test-app.app-cfisbtest.it-platforms.net
```
The entry for spring-music is in red and the one for test-app is in orange.

cf push for spring-music gives me a Staging Error:
```
$:~/my-bosh/spring-music$ cf push -b https://github.com/cloudfoundry/java-buildpack.git
Using manifest file /home/ubuntu/my-bosh/spring-music/manifest.yml

Updating app spring-music in org openstackindia / space development as admin...
OK

Uploading spring-music...
Uploading app files from: /tmp/unzipped-app470278174
Uploading 457.1K, 88 files
Done uploading
OK

Stopping app spring-music in org openstackindia / space development as admin...
OK

Warning: error tailing logs
Error dialing traffic controller server: Forbidden port.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.sys-cfisbtest.it-platforms.net:4443).
Starting app spring-music in org openstackindia / space development as admin...

FAILED
Error restarting application: StagingError

TIP: use 'cf logs spring-music --recent' for more information
```

A look at the logs in dea_next shows me this:
```
{"timestamp":1467112410.9621913,"message":"staging.task.execute-staging.failed","log_level":"error","source":"Staging","data":{"app_guid":"619aad75-d03a-49ba-8ebc-35b9653e0ba0","task_id":"8a543730c86845ae88e9868fa6d4687a","error":"Script exited with status 1"},"thread_id":47044980529560,"fiber_id":47044996087500,"process_id":25808,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":252,"method":"rescue in block in promise_stage"}
{"timestamp":1467112410.9637773,"message":"staging.task-info.copying-out","log_level":"info","source":"Staging","data":{"app_guid":"619aad75-d03a-49ba-8ebc-35b9653e0ba0","task_id":"8a543730c86845ae88e9868fa6d4687a","source":"/tmp/staged/staging_info.yml","destination":"/var/vcap/data/dea_next/staging/d20160628-25808-nxsoxy/staging_info.yml"},"thread_id":47044980529560,"fiber_id":47044993302200,"process_id":25808,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":271,"method":"block in promise_staging_info"}
{"timestamp":1467112410.9931173,"message":"Error copying files out of container: command exited with failure","log_level":"warn","source":"Staging","data":{"app_guid":"619aad75-d03a-49ba-8ebc-35b9653e0ba0","task_id":"8a543730c86845ae88e9868fa6d4687a"},"thread_id":47044980529560,"fiber_id":47044993302200,"process_id":25808,"file":"/var/vcap/packages/dea_next/lib/dea/task.rb","lineno":127,"method":"rescue in copy_out_request"}
{"timestamp":1467112410.9934552,"message":"staging.task-log.copying-out","log_level":"info","source":"Staging","data":{"app_guid":"619aad75-d03a-49ba-8ebc-35b9653e0ba0","task_id":"8a543730c86845ae88e9868fa6d4687a","source":"/tmp/staged/logs/staging_task.log","destination":"/var/vcap/data/dea_next/staging/d20160628-25808-nxsoxy/staging_task.log"},"thread_id":47044980529560,"fiber_id":47044993151820,"process_id":25808,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":262,"method":"block in promise_task_log"}
{"timestamp":1467112411.0259535,"message":"staging.task.failed","log_level":"info","source":"Staging","data":{"app_guid":"619aad75-d03a-49ba-8ebc-35b9653e0ba0","task_id":"8a543730c86845ae88e9868fa6d4687a","error":"Script exited with status 1","backtrace":["/var/vcap/packages/dea_next/lib/container/container.rb:185:in `link_or_raise'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:249:in `block in promise_stage'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `call'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `block in run'"]},"thread_id":47044980529560,"fiber_id":47044997244620,"process_id":25808,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":58,"method":"block in start"}
{"timestamp":1467112411.0270207,"message":"Saving snapshot took: 0.001s","log_level":"debug","source":"Dea::Snapshot","data":{},"thread_id":47044980529560,"fiber_id":47044997244620,"process_id":25808,"file":"/var/vcap/packages/dea_next/lib/dea/snapshot.rb","lineno":41,"method":"save"}
```

Not sure what to make of it.

**Comment by DennisDenuto** [comment]
Hi @srinat999 

Are you able to provide the logs from: `cf logs spring-music --recent`?

Based on the staging output, It looks like you were unable to reach the `traffic controller server`. Specifically the machine on which you ran the staging command: `cf push -b https://github.com/cloudfoundry/java-buildpack.git` needs to be able to talk to  the `traffic controller server`

We think this might be due to your proxy server blocking traffic. Are you able to do the following:

1) Provide us the output from the following command: `CF_TRACE=true cf logs spring-music`
2.1) Log on to CloudController
2.2) Run the following command: `tcpdump  -vvvv -A -s 1024 and tcp -w /tmp/cc_tcpdump.log`
2.3) In a different window, run `cf apps`
2.4) Provide us the file ` /tmp/cc_tcpdump.log` from CloudController (created by step 2.2)

Thanks
Dennis && @dsabeti 
CF Release Integration Team

**Comment by srinat999** [comment]
Thanks guys. I managed to get the entire installation up and running. 

This particular problem was because of insufficient memory for my app. Bumped it to 1G from 512M and it worked. Also fixed my log issue. The problem there was my public endpoint (api.sys-cfisbtest.it-platforms.net) wasn't getting resolved in the logaggregator VM. Fixed that it worked like a charm!

**Comment by JesseTAlford** [comment]
Glad to hear you got it working, @srinat999. Please feel free to open issues on any problems you encounter in the future!
