### ISSUE TITLE
Errors when bosh create release

### ISSUE THREAD

**Issue by YuPengZTE** [cloudfoundry/cf-release#998]
```
root@agent-id-bosh-0:/home/vagrant/contribute/cf-release# bosh create release
Syncing blobs...
debian_nfs_server/nfs-kernel-server_1%3a1... downloaded
uaa/cloudfoundry-identity-varz-1.0.2.war downloaded
nginx/nginx-upload-module-2.2.tar.gz downloaded
uaa/newrelic.jar downloaded
uaa/apache-tomcat-7.0.61.tar.gz downloaded
haproxy/haproxy-1.5.14.tar.gz downloaded
haproxy/pcre-8.37.tar.gz downloaded
uaa/cloudfoundry-identity-statsd-1.0.0.wa... downloaded
ruby-2.1.8/bundler-1.9.4.gem downloaded
ruby-2.1.8/ruby-2.1.8.tar.gz downloaded
ruby-2.1.8/yaml-0.1.6.tar.gz downloaded
postgres/postgresql-9.4.6.tar.gz downloaded
golang/go1.6.1.linux-amd64.tar.gz downloaded
golang/go1.5.4.linux-amd64.tar.gz downloaded
openjdk/openjdk-1.8.0_91-x86_64-trusty.ta... downloaded
openjdk/openjdk-1.8.0_91-x86_64-mountainl... downloaded
libmariadb/libmariadb-5.5.36.tar.xz downloaded
nginx/newrelic_nginx_agent-1.2.1.tar.gz downloaded
ruby-2.2.5/ruby-2.2.5.tar.gz downloaded
ruby-2.2.5/bundler-1.11.2.gem downloaded
ruby-2.2.5/yaml-0.1.6.tar.gz downloaded
ruby-2.3/bundler-1.11.2.gem downloaded
ruby-2.3/ruby-2.3.1.tar.gz downloaded
ruby-2.3/rubygems-2.6.4.tgz downloaded
binary-buildpack/binary_buildpack-cached-... downloaded
go-buildpack/go_buildpack-cached-v1.7.8.z... downloaded
java-buildpack/java-buildpack-v3.7.1.zip downloaded
java-buildpack/java-buildpack-offline-v3.... downloaded
python-buildpack/python_buildpack-cached-... downloading 255.2M (5%)
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/base.rb:63:in `rescue in get': Failed to fetch object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired> /usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `sysread' (Bosh::Blobstore::BlobstoreError)
/usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `readpartial'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:364:in `readpartial'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:957:in `block in read_body_length'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:955:in `read_body_length'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient/session.rb:703:in `get_body'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:1092:in `do_get_block'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:891:in `block in do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:985:in `protect_keep_alive_disconnected'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:890:in `do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:778:in `request'
/var/lib/gems/1.9.1/gems/httpclient-2.4.0/lib/httpclient.rb:677:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/simple_blobstore_client.rb:39:in `get_file'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/base.rb:50:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `call'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `block in retryer'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `loop'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `retryer'
/var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:316:in `download_blob'
/var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `call'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `loop'
/var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/base.rb:49:in `get'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `call'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:28:in `block in retryer'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `loop'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/retryable.rb:26:in `retryer'
        from /var/lib/gems/1.9.1/gems/blobstore_client-1.3062.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
        from /var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:316:in `download_blob'
        from /var/lib/gems/1.9.1/gems/bosh_cli-1.3062.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `call'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `loop'
        from /var/lib/gems/1.9.1/gems/bosh_common-1.3062.0/lib/common/thread_pool.rb:63:in `block in create_thread'
        from /var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from /var/lib/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

root@agent-id-bosh-0:/home/vagrant/contribute/cf-release# bosh create release
Syncing blobs...
python-buildpack/python_buildpack-cached-... downloading 255.2M (49%)
                                             downloading 255.2M (50%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (109%)
                                             downloading 255.2M (110%)
                                             downloading 255.2M (110%)
                                             downloading 255.2M (137%)
                                             downloading 255.2M (137%)
                                             downloading 255.2M (137%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (139%)
                                             downloading 255.2M (165%)
                                             downloading 255.2M (307%)
```

**Comment by Amit-PivotalLabs** [comment]
Hi @YuPengZTE 

This is a known issue with the `bosh` CLI.  I will migrate your issue to the BOSH repository.

Best,
Amit
